### ISSUE TITLE
Create Wildfly adapter module

### ISSUE THREAD

**Issue by aguibert** [MicroShed/microshed-testing#104]
**Describe the solution you'd like**
Currently the OpenLiberty and Payara runtimes have dedicated modules that provide some helpful default configuration like:
 - default ports
 - default dockerfile instructions

It would be nice if Wildfly also had a default module so users are not required to have a Dockerfile

**Describe alternatives you've considered**
It is still possible to use MicroShed Testing on a Wildfly app without a dedicated Wildfly adapter module, but this relies on:
 - Inspecting the docker container for exposed port on each run (adds about a second to the test runtime)
 - the user having a Dockerfile in their repo (if building the app from source)

**Additional context**
Write an adapter involves implementing the `org.microshed.testing.testcontainers.spi.ServerAdapter` interface in a new module. See the [Payara micro](https://github.com/MicroShed/microshed-testing/tree/master/modules/payara-micro) adapter for a minimal example

**Comment by rieckpil** [comment]
@aguibert I would like to contribute to your project. Can I pick this issue?

**Comment by aguibert** [comment]
sure! I'll go ahead and assign it to you

**Comment by aguibert** [comment]
Implemented in PR #128
