### ISSUE TITLE
allow basic authentication header on injected @RESTClients

### ISSUE THREAD

**Issue by jlf-ibm** [MicroShed/microshed-testing#157]
**Is your feature request related to a problem? Please describe.**

We already support attaching JWTs to RESTClient instances. Allow another type in that same vein, for setting HTTP Basic Authentication header.

**Describe the solution you'd like**

```
@RESTClient
@BasicAuthConfig(username = "user", password="pass")
MyClientResource myClient;
```

**Describe alternatives you've considered**

The only alternative is to completely change my application to use JWTs instead of in-container basic authentication.

**Additional context**

Open Liberty 19 with standard LDAP registry and web.xml with ALL_CONFIDENTIAL protecting /*

**Comment by aguibert** [comment]
Thanks for opening this @jlf-ibm, sounds like a good use case to support. I wonder if we should use a more generic annotation approach so we don't need to make a new annotation for every authentication or header type?

**Comment by jlf-ibm** [comment]
Maybe if we add a third? I leave it to you. It'd be nice to just get this specific in sooner than a generic later.

**Comment by aguibert** [comment]
Hi @jlf-ibm, I wrote up a proposed PR here and will merge it soon:
https://github.com/MicroShed/microshed-testing/pull/158
