### ISSUE TITLE
Test an app that uses HTTPS

### ISSUE THREAD

**Issue by aguibert** [MicroShed/microshed-testing#17]
## User story: 
As a user of this test framework, I want to test an app that uses HTTPS

## Additional detail:
The easiest way to test an HTTP service is using unsecured applications, but in production applications should be communicating via HTTPS, which requires client/server certificates. The test framework should make it easy to drive HTTPS requests to the server.

**Comment by aguibert** [comment]
It may be good to use a Pebble container for generating certificats using the ACME protocol for testing:
https://github.com/letsencrypt/pebble

**Comment by appiepollo14** [comment]
Same issue as https://github.com/MicroShed/microshed-testing/issues/306 therefore this one will be closed.
