### ISSUE TITLE
JWT keygen slow - consider triggering with something other than use of SharedContainerConfiguration

### ISSUE THREAD

**Issue by scottkurz** [MicroShed/microshed-testing#202]
I'm noticing that, the math involved to do keygen in `JwtBuilder.getPublicKey()` can be slow, especially when a debugger is attached.  

Since shared container config is fundamentally about reuse of config across test classes (rather than JWT), maybe there's a better way to decide we should do keygen than just looking for the presence of **SharedContainerConfiguration** ?

https://github.com/MicroShed/microshed-testing/blob/b31af235877f41ea06701c58bad4e2119a3284f2/modules/testcontainers/src/main/java/org/microshed/testing/testcontainers/config/TestcontainersConfiguration.java#L170-L172

My last run was with an IBM V8 JDK, but haven't been carefully keeping track.

Maybe we could leave this open and see how big a deal it is, and see if there's a motivation to address.

**Comment by aguibert** [comment]
I think it would be good to investigate why building a public key is so slow when a debugger is attached, rather than trying to minimize the scenarios it is needed for. Perhaps you need to set ` -Djava.security.egd=file:/dev/./urandom` on your JVM?

**Comment by aguibert** [comment]
Closing this issue for now since there hasn't been any new activity. We can re-open if more information is presented in the future
