### ISSUE TITLE
Need custom header / authorization support

### ISSUE THREAD

**Issue by honeyfordd** [MicroShed/microshed-testing#207]
**Is your feature request related to a problem? Please describe.**
Our system relies on an authorization mechanism that isn't either basic auth or JWT. If you are using something other than those two methods then unless the Authorization parameter is a named method parameter then there's currently no way to set it to anything other than either a username / password or a JWT. 

**Describe the solution you'd like**
It would be great if it was possible to specify some HTTP headers when calling a test or be able to specify a handler method that gets called just before the REST call so that it was possible to manipulate the request headers etc. Ideally this would work for dynamic values where they are generated at test time rather than being static as per the current @BasicAuthConfig and the @JwtConfig. 
**Describe alternatives you've considered**
The only way that I can currently get this to work is to add a header parameter onto each of my REST methods so that I can pass this value in on calling the test e.g. public Response getAccount(@HeaderParam("Authorization") String authorisationParameter).

**Additional context**
We are using a ContainerRequestFilter to process the authorization header and check the value which means that we don't have to handle this in each specific method. See example code below:

```java
@Provider
@Priority(Priorities.AUTHENTICATION)
public class SecurityFilter implements ContainerRequestFilter {

   @Override
    public void filter(ContainerRequestContext requestContext) throws IOException
    {
        Method method = resourceInfo.getResourceMethod();
        // access allowed for all methods that @PermitAll
        if( ! method.isAnnotationPresent(PermitAll.class))
        {
            // access denied for all methods that @DenyAll
            if (method.isAnnotationPresent(DenyAll.class))
            {
                requestContext.abortWith(Response.status(Response.Status.FORBIDDEN)
                        .entity("Access denied").build());
                return;
            }

            // for any others that have the @RolesAllowed annotation then check the token

            // fetch authorization header which should contain the bearer token
            final MultivaluedMap<String, String> headers = requestContext.getHeaders();
            final List<String> authorization = headers.get(AUTHORIZATION_PROPERTY);
            ....
```

**Comment by aguibert** [comment]
hi @honeyfordd, thanks for raising this idea.

If the current annotations (`@BasicAuthConfig` and `@JwtConfig`) are not sufficient, you can use [RestClientBuilder ](https://www.javadoc.io/doc/org.microshed/microshed-testing-core/latest/org/microshed/testing/jaxrs/RestClientBuilder.html)to programmatically construct your REST Clients, including applying any custom headers. 

For example:
```java
MyService svc = new RestClientBuilder()
        .withHeader("foo", "bar")
        .withProviders(SecurityFilter.class)
        .build(MyService.class);
```

**Comment by honeyfordd** [comment]
@aguibert Thanks for responding and sorry for the late reply. I didn't realise that was possible but I've implemented as per your suggestion and that's done exactly what we needed so is definitely sufficient for our use case. I can dynamically create a single client per test to use that contains our token set with withHeader and that's hitting our SecurityFilter just fine.
