### ISSUE TITLE
Update Quarkus 1.6.1.Final makes @RESTClient be null

### ISSUE THREAD

**Issue by tiagomistral** [MicroShed/microshed-testing#208]
**Describe the bug**
At this point after downloading the microshed quarkus-app and updating quarkus to the latest version, it will result in an NPE in all tests that include the @RESTClient annotation.

**To Reproduce**
1. Download latest version of microshed quarkus-app (https://github.com/MicroShed/microshed-testing/tree/master/sample-apps/quarkus-app)
2. Update the quarkus-plugin.version and quarkus.platform.version properties to 1.6.1.Final.
3. Run 'mvn verify'

**Expected behavior**
Should run without NPE errors.

**System information:**
 - OS:Mac
 - Java Version: 11
 - MicroShed Testing Version: 0.9

**Additional context**
I use the @Inject annotation as workaround and seems fine.

**Comment by aguibert** [comment]
hi @tiagomistral, thanks for raising this issue. Looks like the same problem as #181 so I'm going to close this as a duplicate. The issue will be fixed by #223
