### ISSUE TITLE
Access the container from the SharedContainerConfig

### ISSUE THREAD

**Issue by max-weis** [MicroShed/microshed-testing#217]
I would like to test the logs from a container I defined in the `SharedContainerConfig` class. Testcontainers provides the WaitingConsumer class, which allows me to follow and read the logs from my tests.

Is there a way to get the shared container defined in the `SharedContainerConfig` class?

**Comment by aguibert** [comment]
hi @max-weis, normally containers in the `SharedContainerConfig` class are defined as `public static` so they can be accessed from any other class statically. Does this work for you?

**Comment by max-weis** [comment]
Just tried that. Yes, it works. In vanilla Testcontainers I usually define the container as `private static` and inherit from the "ConfigClass".
If that is how you define Container in MicroShed, than it answers my question. Thanks!

**Comment by aguibert** [comment]
great, thanks! Closing this issue
