### ISSUE TITLE
Upgrade to Test Containers 1.15

### ISSUE THREAD

**Issue by rdebusscher** [MicroShed/microshed-testing#239]
testContainers < 1.15 fails to run on Docker Desktop for Mac 2.4

   ./gradlew :microshed-testing-jaxrs-json:test

Results in 

```
Gradle Test Executor 1 > JaxrsJsonIT STANDARD_OUT
    0 INFO org.microshed.testing.jupiter.MicroShedTestExtension  - Using ApplicationEnvironment class: org.microshed.testing.testcontainers.config.TestcontainersConfiguration
    6640 WARN org.testcontainers.utility.ResourceReaper  - Can not connect to Ryuk at localhost:32869
```

See https://github.com/testcontainers/testcontainers-java/issues/3166

**Comment by rdebusscher** [comment]
I'm unable to create a PR due to the Github WorkFlow configuration file (Push to Github fork fails)

Here is the Patch

[patch.diff.zip](https://github.com/MicroShed/microshed-testing/files/5542416/patch.diff.zip)

**Comment by aguibert** [comment]
Thanks for reporting this issue @rdebusscher , I've made the necessary updates and published them in a new version -- 0.9.1.

Can you please elaborate on the issues you had trying to raise a PR though? If other people are having problems contributing fixes, I want to make sure that gets fixed.

**Comment by rdebusscher** [comment]
@aguibert When performing `git push` I get the following error to my clone repo

````
(refusing to allow an OAuth App to create or update workflow `.github/workflows/microshed-ci.yml` without `workflow` scope)
````

But it seems I get this only when using the tool `sourcetree`, when I do it on the command line, it works ok.

**Comment by rdebusscher** [comment]
Thanks for releasing a new version with the fix!
