### ISSUE TITLE
Support Jakarta namespace

### ISSUE THREAD

**Issue by KyleAure** [MicroShed/microshed-testing#292]
**Is your feature request related to a problem? Please describe.**
Currently, microshed testing uses the Java EE namespace (javax.) for RESTful web services and Web Token integration.

**Describe the solution you'd like**
We should release a separate version of microshed for the Jakarta EE namespace (jakarta.)

**Comment by KyleAure** [comment]
@appiepollo14 I am likely going to be taking on this issue but I wanted to ask for your input. 
For your use case are your applications still using javax or jakarta package names?

I ask because we have two options here:
1. Support both javax and jakarta
2. Support only jakarta

**Comment by appiepollo14** [comment]
You were just a few seconds before me. I wanted to mention I'm willing to help out on this one. If you ask me personally, jakarta only would be fine. In practice, I think support for both is needed. Isn't it as simple as create a seperate module for jakarta? Or how are you thinking about setting this up?

**Comment by KyleAure** [comment]
I'd probably have to do some more research.  Eclipse has a transformer that can automatically transform java byte code from javax to jakarta.  If we could use that then we don't have to duplicate anything and we can just transform and upload both.  Which sounds simple but needs some investigation.

**Comment by appiepollo14** [comment]
@KyleAure this is only for the jaxrs part of the core right?

**Comment by KyleAure** [comment]
Correct, but we could add in other javaee/jakartaee features later so I want to come up with a general solution.

**Comment by appiepollo14** [comment]
@KyleAure than just go for Jakarta only IMHO. Great work on this pr so far! The payara base image needs updating to be able to run j11.
