### ISSUE TITLE
Release 0.9.2 [Proposal]

### ISSUE THREAD

**Issue by KyleAure** [MicroShed/microshed-testing#297]
I don't think we are ready for a 1.0 release yet so let us target our next release at version 0.9.2

Here is some work that will need to be done to get this project back on track for another release: 
- [x] (Highest priority) Get the [GitHub Actions CI](https://github.com/MicroShed/microshed-testing/blob/master/.github/workflows/microshed-ci.yml) build working so we can verify future updates
- [x] #65 so we can have a instructions for committers  
- [x] #299
- [x] Update our dependencies (Testcontainers is currently on 1.19.1)
- [x] Rename default branch to main
- [x] Resolve outstanding dependabot issues
- [x] #311
- [x] #309
- [x] #292
- [x] Make sure maven example app dependencies are up-to-date and managed by dependabot.

If we can get this housekeeping taken care of and introduce Jakarta support I think we'll be in a good position to do a new release and get some more community support. 

If there are any other issues that the community thinks needs to be included in the 0.9.2 release please comment below for it to be considered.

**Comment by KyleAure** [comment]
FYI @appiepollo14

**Comment by appiepollo14** [comment]
Hi @KyleAure how are you building the project locally? I keep getting an error that testcontainers can't find a docker env. IMO I've set my environment correctly. Maybe describe this in the contribution.md file aswell.

**Comment by KyleAure** [comment]
@appiepollo14 Is docker running locally on your system?  Unfortunately, I am also unable to build this project locally since I use Colima and the current version of Testcontainers in this project does not support Colima.  I'll try updating testcontainers and see if I can get something working.

**Comment by appiepollo14** [comment]
Yes I'm running docker and/or podman on my machine.

**Comment by appiepollo14** [comment]
@KyleAure does this commit: https://github.com/MicroShed/microshed-testing/commit/1d1485731aeb98a8dee458a97a8d82e6003def0e solve the last checkbox on the list?

**Comment by KyleAure** [comment]
It sure does.  Now to figure out how to do a release :)

**Comment by appiepollo14** [comment]
@KyleAure it doesn't, I saw errors in the dependabot maven task. I've opened a PR for this change.

**Comment by appiepollo14** [comment]
@KyleAure I believe it is simply removing "SNAPSHOT" from the current version in build.gradle and let CI run

ext.currentVersion = '0.9.2-SNAPSHOT'
ext.lastRelease = '0.9.1'

**Comment by appiepollo14** [comment]
@KyleAure How did you manage to start the release process?

**Comment by KyleAure** [comment]
I'm working with the owners of the Microshed org to get a release build started.
I don't have access to push to the Maven repository.

**Comment by appiepollo14** [comment]
@KyleAure any progress on this impediment?
