### ISSUE TITLE
DCO step in CI removal

### ISSUE THREAD

**Issue by appiepollo14** [MicroShed/microshed-testing#315]
@KyleAure there is a step named: DCO in the CI of this project. Causing the CI to appear failed, even thought the Github workflow has succeeded. Please remove this check from the CI to give a better report of CI failing/succeeding. IMO there is no value in this check. What are your thoughts?

**Comment by KyleAure** [comment]
No, the contribution.md file explains this check. Every commit must be signed and that is what that workflow is checking. 

Please start signing your commits so we can give you proper credit for the work you've put in to this project

**Comment by appiepollo14** [comment]
@KyleAure thanks for the explanation. I've already started signing so that will be okay.
