### ISSUE TITLE
Jakarta first refactor 

### ISSUE THREAD

**Issue by KyleAure** [MicroShed/microshed-testing#400]
I think for forward development we should take a Jakarta first approach.
Since 0.9.2 was my first release as lead on this project I wanted to have at least one release were we could transition from Java EE to Jakarta EE.

Going forward I am fine dropping Java EE support.

- [ ] All integrations tests (sample-apps/) should be converted to Jakarta except the everything-app.
- [ ] Stabilize the everything-app to depend on microshed-testing-core:0.9.2
- [ ] Copy source code from microshed-testing-core to microshed-testing-core-jakarta
- [ ] Manually transform it to Jakarta namespace
- [ ] Delete microshed-testing-core

**Comment by appiepollo14** [comment]
Great decision, will de my best to help with this!

**Comment by appiepollo14** [comment]
@KyleAure as mentioned earlier. I would like to convert the core to the Jakarta namespace and drop the newly created core-Jakarta module. Modules should be based on functionality not on the technical implementation. In this way, core will stay core and from version 0.9.3 will be supporting Jakarta not Javax. Agreed?

**Comment by KyleAure** [comment]
Yes I think this will be the best solution.

**Comment by appiepollo14** [comment]
Hi Kyle, Please alter to tasks to comply to what we've decided on. I've opened a draft PR to show the progress. Happy holidays!

**Comment by appiepollo14** [comment]
@KyleAure PR is ready for your approval.
