### ISSUE TITLE
Drop Quarkus support

### ISSUE THREAD

**Issue by appiepollo14** [MicroShed/microshed-testing#410]
Quarkus has a solution built in which perfectly enables the user to execute integration tests with dependant infrastructure. Therefore I would suggest dropping support for Quarkus to keep this project as lean as possible.

**Comment by KyleAure** [comment]
If I think about the use case from an application developer point of view if I want to test my application on any application server I would want to use the same test infrastructure for all my tests.  

I think removing Quarkus support would make this project less appealing for that use case.

**Comment by appiepollo14** [comment]
The point is that Quarkus doesn't run on an Application Server and is able to run IntegrationTests out of the box. Just like Spring which we don't support. Therefore I believe there is no usecase for Quarkus.

**Comment by appiepollo14** [comment]
@KyleAure whats the verdict?

**Comment by KyleAure** [comment]
I don't think removing functionality from this project is a worthwhile venture.  If people are using Microshed Testing instead of the build in quarkus testing framework then we should keep supporting it.

**Comment by appiepollo14** [comment]
@KyleAure I've my doubts it is used but mkay. I see a point in using MicroShed for 'older' applications running on Application servers. Cloud native apps like Spring and Quarkus will not use this.
