### ISSUE TITLE
Requires MP Health 2.0 / MicroProfile 3.0 runtime

### ISSUE THREAD

**Issue by rdebusscher** [MicroShed/microshed-testing#48]
According to the readme, the goal is

> - Work with any JavaEE or MicroProfile runtime

But it requires MP Health 2.0 due to the fact that it checks for readiness of the container using **/health/ready**

So the goals must be adjusted, or the check must be made configurable.

**Comment by aguibert** [comment]
resolved by https://github.com/MicroShed/microshed-testing/issues/59
