### ISSUE TITLE
Change name of `MicroProfileApplication` since it can be used for any application, also Java EE

### ISSUE THREAD

**Issue by rdebusscher** [MicroShed/microshed-testing#63]
`MicroProfileApplication` is not the best name since you can just run any application. 

But is has some benefits over GenericContainer like detecting the file to deploy, the dockerFile or the Server Adapter.

**Comment by rdebusscher** [comment]
Proposal : ApplicationContainer

Since it still is a Container but geared towards your application.

**Comment by aguibert** [comment]
yes I think we certainly need to change it away from MicroProfileApplication, or possibly offer multiple options. that extend a base abstract class.

I like `ApplicationContainer`, or perhaps just `ApplicationRuntime` may be more appropriate when not running in containers for hollow mode (see [this doc ](https://microshed.org/microshed-testing/features/02_ApplicationEnvironment.html)for details)

**Comment by yeekangc** [comment]
+1 to either Application, ApplicationContainer or ApplicationRuntime.

Andy, are you thinking that ApplicationRuntime will cover both the container case and hollow mode?  Or, we will have both?

**Comment by aguibert** [comment]
One would cover both

**Comment by yeekangc** [comment]
IMHO, `ApplicationContainer` may be slightly better than `ApplicationRuntime` since MST may support more than "runtimes" but also "frameworks" etc where applications can run in/on.  Also, we already configuration for hollow mode already.
